[package]
name = "spsolve"
version = "0.1.0"
description = "Solve sparse systems of linear equations"
edition = "2021"

[dependencies]
anyhow = "1"

rlu = { version = "0.4", optional = true }
amd = { version = "0.2", optional = true }
num-traits = { version = "0.2", optional = true }

[features]
# default = ["rlu"]
rlu = ["amd", "dep:rlu", "num-traits"]
