[package]
name = "spsolve"
version = "0.1.0"
description = "Solve sparse systems of linear equations"
edition = "2021"

[dependencies]
anyhow = "1"

rlu = { version = "0.4", optional = true }
amd = { version = "0.2", optional = true }
num-traits = { version = "0.2", optional = true }

lufact = { version = "0.1", optional = true }
amd_sys = { version = "0.1", optional = true }

[dev-dependencies]
num-traits = "0.2"

[features]
# default = ["lufact", "rlu"]
rlu = ["dep:amd", "dep:rlu", "dep:num-traits"]
lufact = ["dep:amd_sys", "dep:lufact"]
