[package]
name = "spsolve"
version = "0.1.0"
description = "Solve sparse systems of linear equations"
edition = "2021"

[dependencies]
anyhow = { version = "1", optional = true }
rlu = { version = "0.4", optional = true }
amd = { version = "0.2", optional = true }
num-traits = { version = "0.2", optional = true }

[features]
rlu = ["amd", "dep:rlu", "num-traits", "anyhow"]
